### ISSUE TITLE
Is this SDK recommended by Microsoft 

### ISSUE THREAD

**Issue by adityasahver** [lucadruda/iotc-nodejs-device-client#11]
Hey Luca, 

I see that you have done really great job in writing the Nodejs sdk and making it open source. Wanted to check if this is supported by Microsoft ? In the following link - https://docs.microsoft.com/en-us/azure/iot-central/core/tutorial-connect-device NodeJs isnt a supported language, hence confirming. 

We are intending to use this in a enterprise level application and hence a confirmation will help. 

Regards,

**Comment by lucadruda** [comment]
Hi,
this SDK is **NOT** officially supported by Microsoft even if actively maintained and aligned with latest features.
The official Azure IoT SDK for Node.Js ([https://github.com/Azure/azure-iot-sdk-node](https://github.com/Azure/azure-iot-sdk-node)) is encouraged when creating production-scale applications.

However this IoTC SDK wraps the official Azure IoT SDK and simplifies some concepts so it can be a good option for a first prototyping phase without adding unsupported functionalities.
It also merges device connectivity and provisioning in a single operation, which otherwise has to be implemented separately.

**Comment by lucadruda** [comment]
Closing as answered and without activity
